[package]
name = "dxclrecorder"
version = "0.1.0"
edition = "2021"


[dependencies]
dxcllistener = { git = "https://github.com/koarlchen/dxcllistener.git" }
ctrlc = "3.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.6.0"
lazy_static = "1.4.0"
log = "0.4.17"
simplelog = "0.12.0"
time = "0.3.14"