[package]
name = "dxclrecorder"
version = "0.1.0"
edition = "2021"


[dependencies]
dxcllistener = "0.2.0"
ctrlc = "3.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.6.0"
lazy_static = "1.4.0"